# Material3UI Shell lock screen — Hyprlock
general {
    hide_cursor = true
    grace = 2
    disable_loading_bar = true
}

background {
    monitor =
    color = rgb(111318)
    blur_passes = 4
    blur_size = 8
    noise = 0.018
    contrast = 1.08
    brightness = 0.72
}

label {
    monitor =
    text = cmd[update:1000] date '+%H:%M'
    color = rgb(e2e2e9)
    font_size = 78
    font_family = JetBrainsMono Nerd Font
    position = 0, 105
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date '+%A, %d %B'
    color = rgb(c3c6d0)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 43
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:10000] whoami
    color = rgb(e2e2e9)
    font_size = 17
    font_family = JetBrainsMono Nerd Font
    position = 0, -44
    halign = center
    valign = center
}

shape {
    monitor =
    size = 390, 118
    color = rgb(1d2027)
    border_color = rgb(8d9099)
    border_size = 1
    rounding = 28
    position = 0, -105
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 330, 52
    outline_thickness = 0
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(1d2027)
    inner_color = rgb(282b33)
    font_color = rgb(e2e2e9)
    check_color = rgb(b9c4ff)
    fail_color = rgb(ffb4ab)
    placeholder_text = <i>Unlock Material3UI Shell</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fade_on_empty = false
    rounding = 20
    position = 0, -105
    halign = center
    valign = center
}

label {
    monitor =
    text = Material3UI Shell
    color = rgb(b9c4ff)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -205
    halign = center
    valign = center
}

label {
    monitor =
    text = Locked · Material3UI Shell
    color = rgb(c3c6d0)
    font_size = 13
    font_family = JetBrainsMono Nerd Font
    position = 0, -235
    halign = center
    valign = center
}
